### ISSUE TITLE
Update run_script 

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/wlcg_lightweight_site_wn_pbs#6]
- connect with overlay network

**Comment by ejr004** [comment]
@maany testing the initial changes.

**Comment by maany** [comment]
@ejr004 cool!

**Comment by ejr004** [comment]
Now the script it's able to receive parameters needed to docker images. **We only need to pay attention to the order**: _ip container, hostname container, ip CREAM, hostname CREAM and docker swarm network name_

**Comment by ejr004** [comment]
ie: ./run_lwwn.sh .10.0.1.10 worker-node.cern.ch 10.0.1.5 puppet-server.cern.ch simple

**Comment by ejr004** [comment]
Done !
Tested with:

/etc/simple_dev/wlcg_lightweight_site_wn_pbs/yaim./run_lwwn.sh --ip=10.0.1.10 --host=worker-node.cern.ch --net=simple --node=puppet-server.cern.ch:10.0.1.5

**Comment by maany** [comment]
@ejr004 Added a commit https://github.com/maany/wlcg_lightweight_site_wn_pbs/commit/9eb1ff62a982c200657cbc1ed6e5d600561cb820 

I have reviewed everything as well. Could you add it to your PR using:
```
cd {your_development_directory} #that contains the issue_6 branch
git clone --single-branch -b ejr004-issue_6 https://github.com/maany/wlcg_lightweight_site_wn_pbs ejr004-issue_6
git checkout issue_6
git rebase ejr004-issue_6
git push origin issue_6
```
